### ISSUE TITLE
Allow Any values in fetch_data_by_keys return

### ISSUE THREAD

**Issue by thomasborgen** [greenbird/piri#100]
Our data fetcher makes an assumption that we only want normal values like string/int/bool etc when fetching a value from a key. However, a resent usecase where the value we want to get is actually an `array` makes me want to rethink this limitation.

First i thought we could just remove the following line in collection_handlers.fetch_value_from_key
```python
if isinstance(collection, ValueTypes):  # this line
    return collection  # type: ignore
```

But this would allow any value of any key to be mapped to an attribute. This means that even json objects can be mapped.

to prevent this we could instead add a check if value is list of ValueTypes, then allow that.

```python
    ...
    if isinstance(collection, ValueTypes):  # type: ignore
        return collection  # type: ignore

    if all([isinstance(val, ValueTypes) for val in collection]):
        return collection
    ...
```

The obvious problem here is that stuff like casting and if statements will not work if you are trying to get a json object.
But... is that piri's problem?

Array values will actually support slicing and if statements[in, is, not], but not casting.

**I'm starting to think that maybe we should drop the valuetype limitation all together and just say that, a user is allowed to map whatever he/she wants to an attribute.**

We would then add tests that confirm for example casting will not work if you try to cast an object, but for example slicing will work when working with an array etc. 

@ChameleonTartu what do you think about this?

**Comment by ChameleonTartu** [comment]
@thomasborgen It took me a while, but I finally find use-case from my experience. It can be the case when you wrap a response with an extra layer on top. For instance, `{"response": { ... } }` but you actually can do `{"data": {"response": { ... }}}`

"Allow complex-types" is a nice feature to have, but instead of dropping type, we need to force explicit type declaration such as an `object` or an `array.` The schema itself becomes stricter, but we will have more control over what is happening. What do you think about it?

Also, when it comes to if statements and alike. Why it cannot work on nested fields, so we can call it on primitive types of complex objects, arrays?

**Comment by thomasborgen** [comment]
@ChameleonTartu 
How about this:
We will remove the type limitation on data found.
We will later add an optional type checker for found data. This way we can have a deterministic way of telling Piri what type the data we want to find is. But not restrict people to find the data hey want.

I will create a new issue for this. But the obvious place we could implement such a feature:
config... 
```json
...{
  mappings: [
    {
      "path": ["path", "to", "data"],
      "required_data_type": "string",
      ... "slicing, if statements default"
    }
  ]
}
```

I think this should be a part of a bigger feature update adding "required" keyword to objects and attributes and will force Piri to Fail.

**Comment by ChameleonTartu** [comment]
@thomasborgen I think this is a great idea! It would mean people can use whatever, and if they need, specify the type explicitly.

**Comment by thomasborgen** [comment]
@ChameleonTartu You were right on the if statements. All if statements work with both arrays and objects. I will update schema to allow `array` and `object` as accepted valuetypes in  `target`, `then` and `else` for if statements
