### ISSUE TITLE
Feature Nested Iterables

### ISSUE THREAD

**Issue by thomasborgen** [greenbird/piri#101]
problem:
Its impossible to iterate over nested data without adding config objects. This is a problem when you don't want to nest your output data.

consider the following input:

```json
{
  "data": [
    {
      "node_id": "id1",
      "node_readings": [
        {
          "reading": "1",
        },
        {
          "reading": "2"
        }
      ]
    },
    {
      "node_id": "id2",
      "node_readings": [
        {
          "reading": "3",
        },
        {
          "reading": "4"
        }
      ]
    }
  ]
}

```

and we want to following output
```json
{
  "my_flat_readings_data": [
    {
      "id": "id1",
      "value": "1"
    },
    {
      "id": "id1",
      "value": "2"
    },
    {
      "id": "id2",
      "value": "3"
    },
    {
      "id": "id2",
      "value": "4"
    },
  ]
}
```

Trying to map that will get you this far until you realize that you can't have a flat data structure since you cannot loop 2 levels in 1 object.
```json
{
  "name": "root",
  "array": false,
  "objects": [
    {
      "name": "my_flat_data",
      "array": true,
      "path_to_iterable": ["data"],
      ...
    }
  ]
}
```

The proposal is a breaking change, changing `path_to_iterable` into `paths_to_iterables: List[List[str, int]]`

This would allow us to write a config like this:
```json
{
  "name": "root",
  "array": false,
  "objects": [
    {
      "name": "my_flat_readings_data",
      "array": true,
      "paths_to_iterables": [["data"], ["data", "node_readings"]],
      "attributes": [
        {
          "name": "id",
          "mappings": [
            {
              "path": ["data", "node_id"]
            }
          ]
        },
        {
          "name": "value",
          "mappings": [
            {
              "path": ["node_readings", "reading"]
            }
          ]
        }
      ]
    }
  ]
}
```

We would still handle the collections objects like we do today where we move them to the root of the data so that the data can be referenced by the last value in their path to iterable.

**Comment by thomasborgen** [comment]
@ChameleonTartu 

What do you think?

we would have to write mapper.map_data() and possibly use a generator that takes input data, and then would iterate through everything and `yield` back dictionaries with each iterable added to a 'key': first_element then next time 'key': second element etc...

It is doable, and would make piri a lot more flexible

**Comment by ChameleonTartu** [comment]
@thomasborgen I have a couple of questions.

1. Will it work like Python `zip` to iterate over the shortest length and then drop the remaining part? Or do you think instead to iterate over the longest and have a list with objects with missing keys (assumingly that we don't force `default` value)

2. Will we limit the number of possible lists?

3. How this work if the JSON formatted this way:

```JSON
{
  "data": [
    {
      "node_id": "1",
      "configs": [{
        "key": "secret_key"
      }]
    }
  ],
  "configs": [
    {
      "key": "public_key"
    }
  ]
}
```

You would have arrays of `configs` on different levels, and need to iterate on both of them? For instance `[["data"], ["configs"], ["data", "configs"]]`


My main questions are regarding the behavior of the functionality. I just realized, the example itself is not `flatMap` but rather a Cartesian product on 1 x N, where N is a length of the list.

**Comment by thomasborgen** [comment]
answering number 3 first.
We have the same issue today, so that will have to be addressed anyways we can have a separate issue for this. And just to clarify the issue is that if you iterate "root.data.configs" then we would actually overwrite the root.configs object.

1. It will work exactly like it works today except we'll be able to do more at once.

How we do it today is that we find a list at path_to_iterable for example like this: ['path', 'to', 'data'] = [{obj1}, {obj2}, {obj3}].
Then we iterate that data and attach it to the root with path_to_iterable's last key:

input:
```json
{
  "path": {
    "to": {
      "data": [
        {"test": "val"},
        {"test": "val2"}
      ]
    }
  }
}
```

1st iteration:
```json
{
  "path": {
    "to": {
      "data": [
        {"test": "val"},
        {"test": "val2"}
      ]
    }
  },
  "data": {"test": "val"}
}
```

2d iteration:
```json
{
  "path": {
    "to": {
      "data": [
        {"test": "val"},
        {"test": "val2"}
      ]
    }
  },
  "data": {"test": "val2"}
}
```

Now with the new configuration we could have the following config and input and get 4 iterations.

config

```json
{
  "name": "root",
  "array": false,
  "objects": [
    {
      "name": "my_flat_readings_data",
      "array": true,
      "paths_to_iterables": [["data"], ["data", "node_readings"]],
      "attributes": [
        {
          "name": "id",
          "mappings": [
            {
              "path": ["data", "node_id"]
            }
          ]
        },
        {
          "name": "value",
          "mappings": [
            {
              "path": ["node_readings", "reading"]
            }
          ]
        }
      ]
    }
  ]
}
```

input
```json
{
  "data": [
    {
      "node_id": "id1",
      "node_readings": [
        {
          "reading": "1",
        },
        {
          "reading": "2"
        }
      ]
    },
    {
      "node_id": "id2",
      "node_readings": [
        {
          "reading": "3",
        },
        {
          "reading": "4"
        }
      ]
    }
  ]
}
```

So after entering the 'my_flat_readings_data' object, we will find the iterable data and send the attributes/objects configuration together with that data.. It will look like this:

1st iteration: 
```json
{
  "data": {
    "node_id": "id1",
    "node_readings": [
      {
        "reading": "1",
      },
      {
        "reading": "2"
      }
    ]
  },
  "node_readings": {
    "reading": "1",
  },
}
```

Notice how "data" is no longer an array, but thats completely fine. rest of the array will still be looped.

2d iteration
```json
{
  "data": {
    "node_id": "id1",
    "node_readings": [
      {
        "reading": "1",
      },
      {
        "reading": "2"
      }
    ]
  },
  "node_readings": {
    "reading": "2",
  },
}
```

3d iteration
```json
{
  "data": {
    "node_id": "id2",
    "node_readings": [
      {
        "reading": "3",
      },
      {
        "reading": "4"
      }
    ]
  },
  "node_readings": {
    "reading": "3",
  },
}
```

4th iteration
```json
{
  "data": {
    "node_id": "id2",
    "node_readings": [
      {
        "reading": "3",
      },
      {
        "reading": "4"
      }
    ]
  },
  "node_readings": {
    "reading": "4",
  },
}
```


We can do this with the current config aswell, but the difference is that we need multiple objects to be able to add more 'path_to_iterable's which also means that the output will have 1 more object.

like the following:

config
```json
{
  "name": "root",
  "array": false,
  "objects": [
    {
      "name": "my_flat_readings_data",
      "array": true,
      "path_to_iterable": ["data"],
      "objects": [
        {
          "name": "not_so_flat",
          "array": true,
          "path_to_iterable": ["data", "node_readings"],
          "attributes": [
            {
              "name": "id",
              "mappings": [
                {
                  "path": ["data", "node_id"]
                }
              ]
            },
            {
              "name": "value",
              "mappings": [
                {
                  "path": ["node_readings", "reading"]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

this would create the exact same output, except that we'd have one more key 'not so flat'

```json
{
  "my_flat_readings_data": [
    {
      "not_so_flat": {"data here"}
    },
    {
      "not_so_flat": {"data here"}
    },
    {
      "not_so_flat": {"data here"}
    },
    {
      "not_so_flat": {"data here"}
    }
  ]
}
```

**Comment by thomasborgen** [comment]
for #105 Nested iterables is working, but still some quirks to handle. 

However, @ChameleonTartu said earlier in this issue that we should consider the fact that its possible to overwrite root level key/values.
I agree now that we should handle this issue in one go, so we don't have two breaking releases.

@msoukup came with an excellent solution that involves changing iterables into objects like this:
```json
{
    "iterables": [
        {
            "alias": "my_alias",
            "path": ["path", "to", "list"]
        }
    ]
}
```

This would give the user the ability to specify their own aliases. Aliases would be the name of the `key` that we put in root that will have each iteration value as its value.

The proposed solution would also make it easy to understand that you can reference your alias for example when adding multiple iterables:

```json
{
    "iterables": [
        {
            "alias": "my_alias",
            "path": ["path", "to", "list"]
        },
        {
            "alias": "my_child",
            "path": ["my_alias", "some_list_with_children"]
        }
    ]
}
```

This structure will also give us a place where we can specify a "required" key for if we want to give the users the possibility to stop processing if a list can't be found.
