### ISSUE TITLE
Building package in edit mode

### ISSUE THREAD

**Issue by vishnu-chalil** [greenbird/piri#133]
I was trying to make some changes to the package in editmode, Iam not able to build piri in edit mode.

I tried cloning it and installing using the following command.

`pip install -e path/to/SomePackage
`
But that was throwing error because setup.py was not there

then I tried to build from git with the forked repo using the following command.

`
py -m pip install -e git+https://github.com/vishnu-chalil/piri.git#egg=piri
`

But this throws

`ModuleNotFoundError: No module named 'setuptools'
`
even though setup tools is already installed. Iam using python 3.7.9.  What is the possible way to get around this?

**Comment by ChameleonTartu** [comment]
Hi @vishnu-chalil, thank you a lot for the question.

We are using [`poetry`](https://python-poetry.org/docs/) as our package manager. 

I recommend patching the package with missing functionality:

- Install `poetry`
- git clone
- go inside the package and do `poetry install`

You will have the package installed, and you can edit, add/remove functionality.

Is there anything you are missing or want to add? Also, I would recommend taking a look at [piri-web](https://github.com/greenbird/piri-web) and [piri-cli](https://github.com/greenbird/piri-cli).

**Comment by vishnu-chalil** [comment]
Thanks @ChameleonTartu . There are  some features Iam looking to addon.

**Comment by ChameleonTartu** [comment]
You can open an issue with a feature request, so we may consider adding them for everyone. To understand some parts of the code, I recommend taking a look at [Railway-Oriented Programming](https://blog.logrocket.com/what-is-railway-oriented-programming/) and [returns](https://github.com/dry-python/returns) package.

**Comment by vishnu-chalil** [comment]
Thanks for the articles @ChameleonTartu . Things looks good to me. Closing this now.
