### ISSUE TITLE
Itarable is not working

### ISSUE THREAD

**Issue by yaniv-trigalo-coupa** [greenbird/piri#136]
examples in documentation for iterable are not working.
https://greenbird.github.io/piri/introduction/#introducing-path-to-iterable
I used the same config and input as the sample and it is not working as expected.

**Comment by thomasborgen** [comment]
Hi, not sure why you don't get the stable version docs in that url, but please try the example that's in the stable docs in `rtd`:
[https://piri.readthedocs.io/en/stable/introduction/#introducing-iterables](https://piri.readthedocs.io/en/stable/introduction/#introducing-iterables) and let me know if it worked.

**Comment by yaniv-trigalo-coupa** [comment]
works with the documentation for 2.1.0, thanks
_____________________________________________________________
Yaniv Trigalo | Sr. Lead Software Engineer | M: 408-431-4884
<https://videos.coupa.com/watch/wRnF5JfLvWTwqry7csZjJ1?>

**Comment by thomasborgen** [comment]
Great!
